version: "3.7"

services:
  astusweb:
    build: ./app
    container_name: astusweb
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./app:/astus/website
    command: "npm run start"
    networks:
      - nuxt-network
  web-server:
   image: nginx:1.17.10-alpine
   container_name: web-server
   volumes:
     - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
     - web-root:/var/www/blowstack
   ports:
     - 80:80
   networks:
     nuxt-network:
   depends_on:
     - astusweb
   restart: always
volumes:
 web-root:
 client-build:
networks:
  nuxt-network:
    driver: bridge