version: "3.7"

services:
  astusweb:
    build: ./app
    container_name: astusweb
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./app:/astus/website
    command: "npm run start"
    networks:
      - nuxt-network
  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    networks:
      nuxt-network:
    depends_on:
      - astusweb
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    
volumes:
 web-root:
 client-build:
networks:
  nuxt-network:
    driver: bridge
